<a href="https://colab.research.google.com/github/arunsprasad/yfcc_tensorflow_beginners/blob/master/yfcc_01_01_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)
print(tf.__version__)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>
2.2.0





***Variables:***

In [2]:
string = tf.Variable("string variable", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(50.568, tf.float64)
print(tf.rank(string))
print(tf.rank(number))
print(tf.rank(floating))
print('-'*60)

rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["test11", "test12"], ["test21", "test22"]])
print('rank1_tensor: ', tf.rank(rank1_tensor))
print('rank2_tensor: ', tf.rank(rank2_tensor))
print('rank2_tensor shape: ', rank2_tensor.shape)


tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
------------------------------------------------------------
rank1_tensor:  tf.Tensor(1, shape=(), dtype=int32)
rank2_tensor:  tf.Tensor(2, shape=(), dtype=int32)
rank2_tensor shape:  (2, 2)




***Matrix:***

In [3]:
tensor1 = tf.ones([1, 2, 3])
tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor3 = tf.reshape(tensor2, [3, -1])

print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)





***Matrix Slicing:***

In [12]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor_matrix = tf.Variable(matrix, dtype=tf.int32)
print(tf.rank(tensor_matrix))
print(tensor_matrix.shape)

print('='*20+'slicing'+'='*20)
print(tensor_matrix[0,2])
print(tensor_matrix[0])
print(tensor_matrix[:,0])
print(tensor_matrix[1::2]) # selects second and fourth row , :: from 1st row every 2nd row will be returned

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)
====================slicing====================
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
